### ISSUE TITLE
1stnorcalcu.org - Banking site

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/HttpsExclusions#3]
https://github.com/AdguardTeam/AdguardFilters/issues/4751

**Comment by ameshkov** [comment]
Done

**Comment by Darina655** [comment]
The message from the client: Upon checking https://github.com/AdguardTeam/AdguardFilters/issues/4751, the issue was marked as CLOSED when in fact, the problem still exists.  In order to complete the business transaction, I must disable Adguard.

**Comment by vozersky** [comment]
@Darina655 

HttpsExclusions are always updated with a new build. Update to beta to see the latest changes. 

But anyway, there is no need to wait or to disable Adguard. User is able to edit exclusions list in Adguard settings. Just go ahead and add an exclusion.
